__pkg_sha256=f4a245b94124b377d8b49646bf421f9155d36aa7614b6ebf83705d3ffc76eaad
__pkg_name=which
__pkg_version=2.21
__pkg_distro_name=gnu-${__pkg_name}-${__pkg_version}
__pkg_src_name=${__pkg_name}-${__pkg_version}
__pkg_tarball_name=${__pkg_name}-${__pkg_version}.tar.gz
__pkg_tarball_url=https://ftp.gnu.org/gnu/${__pkg_name}/${__pkg_tarball_name}
__pkg_configure_extra_args=()
__pkg_build_type=autotools
__pkg_deps=()
__pkg_link_dirs=(bin share)
__pkg_maybe_copy_persistent_config=()
