__pkg_sha256=c25a4838fc8e4c1c8aacb8bd620edb3084a3d63bf8987fdad3ca2758c63240f9
__pkg_name=popt
__pkg_version=1.19
__pkg_distro_name=${__pkg_name}-${__pkg_version}
__pkg_src_name=${__pkg_name}-${__pkg_version}
__pkg_tarball_name=${__pkg_name}-${__pkg_version}.tar.gz
__pkg_tarball_url=https://ftp.osuosl.org/pub/rpm/popt/releases/${__pkg_name}-1.x/${__pkg_tarball_name}
__pkg_configure_extra_args=()
__pkg_build_type=autotools
__pkg_deps=()
__pkg_link_dirs=(include lib share)
__pkg_maybe_copy_persistent_config=()
