__pkg_sha256=60162bd3b9fc6f4886d4c7a07925ffd374167732f55dce8c491bfd9cd818a6cf
__pkg_name=oniguruma
__pkg_version=6.9.9
__pkg_distro_name=${__pkg_name}-${__pkg_version}
__pkg_src_name=onig-${__pkg_version}
__pkg_tarball_name=onig-${__pkg_version}.tar.gz
__pkg_tarball_url=https://github.com/kkos/${__pkg_name}/releases/download/v${__pkg_version}/${__pkg_tarball_name}
__pkg_configure_extra_args=()
__pkg_build_type=autotools
__pkg_deps=()
__pkg_link_dirs=(bin include lib)
__pkg_maybe_copy_persistent_config=()
